# Database Credentials Secret
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: my-namespace
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded value of 'postgres'
  POSTGRES_PASSWORD: NDMyMQ==   # base64 encoded value of '4321'

---

# Application ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-namespace
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db-service:5432/postgres"  # Updated to reference the database service correctly
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "4321"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

---

# PostgreSQL Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: todorovski11/demo
          ports:
            - containerPort: 9090  # Change this to 9090
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
---

# Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: todorovski11/demo
          ports:
            - containerPort: 8081  # Application's container port
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
      imagePullSecrets:
        - name: regcred

---

# Application Service
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: my-namespace
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80              # Exposed service port
      targetPort: 8081      # Application's container port
      nodePort: 30080       # NodePort for external access (adjust if needed)
  type: NodePort

---

# Database Service
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: my-namespace
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80           # The port that the service will expose
      targetPort: 9090   # The port where the application is listening
  type: NodePort        # Internal service for database